# Generated by Django 6.0.4 on 2026-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('arquivo', models.FileField(upload_to='atestados/')),
                ('processado', models.BooleanField(default=False)),
                ('dias_afastado', models.PositiveIntegerField(default=0)),
                ('absenteismo', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Faltas',
        ),
    ]
