# Generated by Django 6.0.4 on 2026-04-17 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atestado_delete_faltas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioComRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administração'), ('gerencia', 'Gerência'), ('logistica', 'Logística'), ('manutencao', 'Manutenção'), ('meio_ambiente', 'Meio Ambiente'), ('operacoes', 'Operações'), ('qualidade', 'Qualidade e Processos'), ('saude', 'Saúde e Segurança'), ('suprimentos', 'Suprimentos')], max_length=20)),
                ('is_gerencia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
