# Generated by Django 6.0.4 on 2026-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atestado_documento_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='atestado',
            name='uf',
            field=models.CharField(choices=[('AC', 'AC - Acre'), ('AL', 'AL - Alagoas'), ('AP', 'AP - Amapá'), ('AM', 'AM - Amazonas'), ('BA', 'BA - Bahia'), ('CE', 'CE - Ceará'), ('DF', 'DF - Distrito Federal'), ('ES', 'ES - Espírito Santo'), ('GO', 'GO - Goiás'), ('MA', 'MA - Maranhão'), ('MT', 'MT - Mato Grosso'), ('MS', 'MS - Mato Grosso do Sul'), ('MG', 'MG - Minas Gerais'), ('PA', 'PA - Pará'), ('PB', 'PB - Paraíba'), ('PR', 'PR - Paraná'), ('PE', 'PE - Pernambuco'), ('PI', 'PI - Piauí'), ('RJ', 'RJ - Rio de Janeiro'), ('RN', 'RN - Rio Grande do Norte'), ('RS', 'RS - Rio Grande do Sul'), ('RO', 'RO - Rondônia'), ('RR', 'RR - Roraima'), ('SC', 'SC - Santa Catarina'), ('SP', 'SP - São Paulo'), ('SE', 'SE - Sergipe'), ('TO', 'TO - Tocantins')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='classificacao',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
