# Generated by Django 6.0.4 on 2026-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atestado_uf_alter_atestado_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomrole',
            name='precisa_alterar_senha',
            field=models.BooleanField(default=True),
        ),
    ]
