# Generated by Django 6.0.4 on 2026-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuariocomrole_precisa_alterar_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestado',
            name='classificacao',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='crm_cro_cress',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='empresa',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='medico',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='nome',
            field=models.CharField(max_length=512),
        ),
    ]
